# Generated by Django 6.0.7 on 2026-07-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=100)),
                ("lname", models.CharField(max_length=100)),
                ("student_class", models.CharField(max_length=10)),
                ("age", models.IntegerField(max_length=3)),
                ("student_number", models.IntegerField(unique=True)),
                ("marks", models.FloatField(max_length=5)),
            ],
        ),
    ]
