# Generated by Django 6.0.7 on 2026-08-03 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="marks",
        ),
    ]
