# Generated by Django 6.0.7 on 2026-08-11 07:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_subject_marks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marks",
            name="score",
            field=models.FloatField(
                max_length=10,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="marks",
            constraint=models.UniqueConstraint(
                fields=("student", "subject"), name="unique_st_sub_mark"
            ),
        ),
    ]
